# Generated by Django 3.2.4 on 2021-07-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210720_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price', 'name'], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
